title: "Dev Caramelo"
description: "Um blog sobre Engenharia de Software e Desenvolvimento"
author: "Eduardo Dalhke Lopes"
email: "your-email@example.com"
baseurl: "/blog-tech"
url: "https://dalhkedu.github.io"
theme: minima

markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, user_url: "https://github.com/dalhkedu" }
    - { platform: linkedin, user_url: "https://linkedin.com/in/eduardo-dalhke" }

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
